const PREFIX_INCREMENT = 'numberList/';

export const GET_NUMBER_LIST_SUCCESS = `${PREFIX_INCREMENT}REQUEST/GET_NUMBER_LIST_SUCCESS`;
export const GET_NUMBER_LIST_REQUEST = `${PREFIX_INCREMENT}REQUEST/GET_NUMBER_LIST_REQUEST`;
export const GET_NUMBER_LIST_FAILURE = `${PREFIX_INCREMENT}REQUEST/GET_NUMBER_LIST_FAILURE`;
